import { db } from '@/config/database';
import type { Knex } from 'knex';

export async function seed(knex: Knex) {
    await knex('tags').del();

    const tags = [
        {
            name: 'React',
            slug: 'react',
            description: 'React JavaScript library for building user interfaces',
            color: '#61DAFB',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'TypeScript',
            slug: 'typescript',
            description: 'TypeScript programming language - typed JavaScript',
            color: '#3178C6',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'JavaScript',
            slug: 'javascript',
            description: 'JavaScript programming language',
            color: '#F7DF1E',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Node.js',
            slug: 'nodejs',
            description: 'Node.js JavaScript runtime',
            color: '#339933',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Performance',
            slug: 'performance',
            description: 'Performance optimization and techniques',
            color: '#F59E0B',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Architecture',
            slug: 'architecture',
            description: 'Software architecture patterns and design',
            color: '#8B5CF6',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Programming',
            slug: 'programming',
            description: 'General programming concepts and practices',
            color: '#EF4444',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'CSS',
            slug: 'css',
            description: 'Cascading Style Sheets for web styling',
            color: '#1572B6',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'HTML',
            slug: 'html',
            description: 'HTML markup language for web structure',
            color: '#E34C26',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Next.js',
            slug: 'nextjs',
            description: 'Next.js React framework for production',
            color: '#000000',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Database',
            slug: 'database',
            description: 'Database design and management',
            color: '#336791',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'API',
            slug: 'api',
            description: 'API design and development',
            color: '#6DB33F',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Testing',
            slug: 'testing',
            description: 'Software testing and quality assurance',
            color: '#C21325',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'DevOps',
            slug: 'devops',
            description: 'DevOps practices and tools',
            color: '#FF6B35',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'Security',
            slug: 'security',
            description: 'Security best practices and vulnerabilities',
            color: '#FFD43B',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
        {
            name: 'UI/UX',
            slug: 'ui-ux',
            description: 'User interface and user experience design',
            color: '#FF6384',
            usage_count: 0,
            is_active: true,
            created_at: new Date(),
            updated_at: new Date(),
        },
    ];

    await db('tags').insert(tags);
    console.log('Tags seeded successfully');
}
